"""Pydantic schemas and models for Browser Worker tasks, reviews, and confirmation tokens."""

from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from job_copilot.domain.browser_worker_enums import BrowserTaskStatus, FieldAction


class BrowserWorkerTaskCreate(BaseModel):
    """Payload for creating a browser execution task."""

    application_id: Optional[str] = Field(default=None, description="Associated application ID")
    job_id: Optional[str] = Field(default=None, description="Associated job ID")
    source: str = Field(default="manual", description="Job portal / platform source")
    target_url: str = Field(description="Target application form URL")
    max_attempts: int = Field(default=3, description="Maximum retry attempts for transient errors")


class DetectedFieldInfo(BaseModel):
    """Information about a detected and processed form field."""

    field_id: str
    element_type: str
    label: Optional[str] = None
    name: Optional[str] = None
    action: FieldAction
    filled_value_masked: Optional[str] = None
    reason: str
    evidence_source: Optional[str] = None


class BrowserTaskReviewPackage(BaseModel):
    """Review package generated by the worker when reaching READY_FOR_REVIEW."""

    task_id: str
    application_id: Optional[str] = None
    job_id: Optional[str] = None
    source: str
    target_url: str
    fields_detected: int
    fields_autofilled: int
    fields_skipped: int
    fields_requiring_user_input: int
    fields_summary: List[DetectedFieldInfo] = Field(default_factory=list)
    selected_resume_artifact_id: Optional[str] = None
    selected_cover_letter_artifact_id: Optional[str] = None
    initial_screenshot_artifact_id: Optional[str] = None
    ready_screenshot_artifact_id: Optional[str] = None
    warnings: List[str] = Field(default_factory=list)
    confirmation_token: Optional[str] = None
    confirmation_expires_at: Optional[datetime] = None
    generated_at: datetime = Field(default_factory=datetime.utcnow)


class HumanConfirmationRequest(BaseModel):
    """Request payload for explicit human confirmation of submission."""

    confirmation_token: str = Field(description="Cryptographic time-limited token issued in review package")
    confirm_text: str = Field(default="SUBMIT", description="Explicit confirmation keyword, must be 'SUBMIT'")
    user_notes: Optional[str] = Field(default=None, description="Optional human operator review notes")


class HumanConfirmationResponse(BaseModel):
    """Response returned upon submission confirmation."""

    task_id: str
    application_id: Optional[str] = None
    success: bool
    status: BrowserTaskStatus
    submission_reference: Optional[str] = None
    submitted_at: Optional[datetime] = None
    message: str


class BrowserTaskResponse(BaseModel):
    """API response model for browser execution tasks."""

    id: int
    task_id: str
    application_id: Optional[str] = None
    job_id: Optional[str] = None
    source: str
    target_url: str
    status: BrowserTaskStatus
    pause_reason: Optional[str] = None
    failure_reason: Optional[str] = None
    attempt_count: int
    max_attempts: int
    review_package: Optional[Dict[str, Any]] = None
    audit_events_count: int
    created_at: datetime
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
