"""Strongly typed Pydantic models for LLM-driven structured resume generation."""


from pydantic import BaseModel, Field


class LLMBulletItem(BaseModel):
    """An individual tailored resume bullet point."""
    text: str = Field(
        description="Action-oriented, impact-driven bullet text formatted for a technical resume. "
                    "May use **bold** markdown to emphasize key technologies and quantified metrics."
    )
    evidence_ids: list[str] = Field(
        default_factory=list,
        description="Exact canonical evidence IDs from the candidate evidence catalog that substantiate this bullet (e.g. ['EXP-HSBC-TF-001'])."
    )
    technologies: list[str] = Field(
        default_factory=list,
        description="Technical skills and tools explicitly mentioned in this bullet."
    )


class LLMProjectItem(BaseModel):
    """A selected and tailored project item."""
    name: str = Field(
        description="Exact canonical name of the project from the candidate profile."
    )
    evidence_ids: list[str] = Field(
        default_factory=list,
        description="Exact canonical evidence IDs for this project (e.g. ['PRJ-MCP-001'])."
    )
    bullets: list[LLMBulletItem] = Field(
        default_factory=list,
        description="1 to 2 tailored bullet points highlighting relevant architecture, tools, and outcomes."
    )
    technologies: list[str] = Field(
        default_factory=list,
        description="Core technologies used in this project."
    )


class LLMSkillGroupItem(BaseModel):
    """A categorized group of technical skills prioritized for the target job."""
    category: str = Field(
        description="Category name (e.g., 'Languages & Frameworks', 'Cloud & DevOps', 'Databases & Distributed Systems', 'Tools & CI/CD')."
    )
    skills: list[str] = Field(
        default_factory=list,
        description="List of verified candidate skills in this category, ordered by relevance to the target job description."
    )


class LLMResumeDraft(BaseModel):
    """Complete structured draft generated by the LLM resume writer."""
    summary: str = Field(
        description="A concise, high-impact 3 to 4 sentence executive professional summary tailored to the target role and company using only verified facts."
    )
    experience_bullets: list[LLMBulletItem] = Field(
        default_factory=list,
        description="Exactly 4 to 5 tailored achievement bullets for HSBC Software Engineer experience, ranked by relevance to the JD."
    )
    projects: list[LLMProjectItem] = Field(
        default_factory=list,
        description="Exactly 2 (or at most 3) most relevant projects selected from the candidate's verified projects."
    )
    skill_groups: list[LLMSkillGroupItem] = Field(
        default_factory=list,
        description="Categorized confirmed skills prioritized and reordered for the target job description."
    )
    dominant_themes: list[str] = Field(
        default_factory=list,
        description="Top 2-3 dominant technical themes identified from the target JD."
    )
    tailoring_rationale: str | None = Field(
        default=None,
        description="Brief explanation of how this resume was tailored to the target JD's key requirements."
    )
