"""Data models for Phase 8 Application Tracking and Outcome Analytics."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


def utc_now() -> datetime:
    """Return timezone-aware current UTC datetime."""
    return datetime.now(timezone.utc)


class ApplicationLifecycleStatus(str, Enum):
    """
    Explicit lifecycle stages of a job application.

    Active Stages (Pipeline Progress):
      - DISCOVERED: Job discovered by Phase 5 ingestion engine.
      - RECOMMENDED: Job evaluated and recommended by Phase 4 intelligence engine.
      - PREPARED: Application package generated by Phase 6 prep engine.
      - READY_FOR_REVIEW: Application reviewed / browser inspection ready (Phase 7).
      - SUBMITTED: Application submitted to employer portal (Phase 7).
      - ACKNOWLEDGED: Employer confirmation received.
      - RECRUITER_RESPONSE: Recruiter reached out for initial discussion.
      - ASSESSMENT: Technical screening, take-home, or coding challenge.
      - INTERVIEW: Interview rounds (technical, behavioral, hiring manager).
      - FINAL_ROUND: Final round / onsite interview.

    Outcome States:
      - OFFER: Formal offer extended by employer.
      - ACCEPTED: Offer accepted by candidate.
      - REJECTED: Application rejected by employer.
      - WITHDRAWN: Application withdrawn by candidate.
      - EXPIRED: Job listing expired or cancelled.

    Archive State:
      - CLOSED: Final archived tracking state.
    """
    DISCOVERED = "DISCOVERED"
    RECOMMENDED = "RECOMMENDED"
    PREPARED = "PREPARED"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    MANUAL_ACTION_REQUIRED = "MANUAL_ACTION_REQUIRED"
    SUBMISSION_UNVERIFIED = "SUBMISSION_UNVERIFIED"
    SUBMITTED = "SUBMITTED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RECRUITER_RESPONSE = "RECRUITER_RESPONSE"
    ASSESSMENT = "ASSESSMENT"
    INTERVIEW = "INTERVIEW"
    FINAL_ROUND = "FINAL_ROUND"
    OFFER = "OFFER"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    WITHDRAWN = "WITHDRAWN"
    EXPIRED = "EXPIRED"
    CLOSED = "CLOSED"


class EventSource(str, Enum):
    """Source that triggered an application event."""
    SYSTEM = "SYSTEM"
    BROWSER = "BROWSER"
    USER = "USER"
    EMAIL = "EMAIL"
    IMPORT = "IMPORT"
    MANUAL = "MANUAL"


class ApplicationEvent(BaseModel):
    """Immutable event record tracking an application lifecycle transition."""
    event_id: str = Field(description="Unique event ID e.g. evt-9d4f10a")
    application_id: str = Field(description="Associated application ID")
    job_id: str = Field(description="Associated job ID")
    event_type: ApplicationLifecycleStatus = Field(description="Lifecycle stage transition")
    timestamp: datetime = Field(default_factory=utc_now, description="When the event occurred")
    source: EventSource = Field(default=EventSource.MANUAL, description="Event source")
    notes: Optional[str] = Field(default=None, description="Optional user or system notes")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Structured event metadata (e.g. round, interviewer)")
    created_at: datetime = Field(default_factory=utc_now)


class ApplicationSnapshot(BaseModel):
    """
    Immutable historical snapshot frozen at submission time.
    Preserves exact match scores, strategy, and artifacts even if algorithms evolve later.
    """
    application_id: str
    job_id: str
    timestamp: datetime = Field(default_factory=utc_now)
    resume_strategy: str
    match_score: float
    recommendation: str
    technical_match: float = 0.0
    responsibility_match: float = 0.0
    seniority_match: float = 0.0
    professional_evidence_match: float = 0.0
    domain_match: float = 0.0
    preference_match: float = 0.0
    credential_match: float = 0.0
    job_source: str = "unknown"
    resume_pdf_path: Optional[str] = None
    cover_letter_path: Optional[str] = None
    applied_via: Optional[str] = None


class ApplicationRecord(BaseModel):
    """Persistent tracking record for a job application."""
    application_id: str
    job_id: str
    company: str
    role: str
    canonical_job_url: Optional[str] = None
    source: str = "unknown"
    discovered_at: Optional[datetime] = None
    recommended_at: Optional[datetime] = None
    prepared_at: Optional[datetime] = None
    submitted_at: Optional[datetime] = None
    current_status: ApplicationLifecycleStatus = Field(default=ApplicationLifecycleStatus.DISCOVERED)
    current_status_at: datetime = Field(default_factory=utc_now)
    mode: str = "ASSISTED"
    resume_strategy: Optional[str] = None

    match_score: Optional[float] = None
    recommendation: Optional[str] = None
    package_path: Optional[str] = None
    browser_session_id: Optional[str] = None
    user_notes: List[str] = Field(default_factory=list)
    snapshot: Optional[ApplicationSnapshot] = None
    events: List[ApplicationEvent] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)


# --- Analytics Schemas ---

class FunnelMetrics(BaseModel):
    """Stage counts in the job application pipeline."""
    discovered: int = 0
    recommended: int = 0
    prepared: int = 0
    ready_for_review: int = 0
    manual_action_required: int = 0
    submission_unverified: int = 0
    submitted: int = 0
    acknowledged: int = 0
    recruiter_responses: int = 0
    assessments: int = 0
    interviews: int = 0
    final_rounds: int = 0
    offers: int = 0
    accepted: int = 0
    rejected: int = 0
    withdrawn: int = 0
    expired: int = 0
    closed: int = 0


class ConversionRates(BaseModel):
    """Conversion percentages across pipeline stages."""
    application_rate: float = Field(0.0, description="Submitted / Discovered (%)")
    response_rate: float = Field(0.0, description="Recruiter Response / Submitted (%)")
    interview_rate: float = Field(0.0, description="Interview / Submitted (%)")
    offer_rate: float = Field(0.0, description="Offer / Submitted (%)")
    acceptance_rate: float = Field(0.0, description="Accepted / Offers (%)")
    is_statistically_reliable: bool = Field(False, description="True if sample size >= 10")
    sample_size_warning: Optional[str] = None


class CohortMetric(BaseModel):
    """Performance metrics grouped by a specific cohort dimension."""
    cohort_name: str
    total_applications: int
    recruiter_responses: int
    interviews: int
    offers: int
    response_rate: float
    interview_rate: float
    offer_rate: float
    is_statistically_reliable: bool = False
    notes: Optional[str] = None


class ResponseTimeMetrics(BaseModel):
    """Elapsed time metrics (in days) between key lifecycle stages."""
    metric_name: str
    sample_count: int
    median_days: float
    mean_days: float
    min_days: float
    max_days: float


class AnalyticsDashboard(BaseModel):
    """Aggregated analytics dashboard summary."""
    total_tracked: int
    funnel: FunnelMetrics
    conversion: ConversionRates
    strategy_performance: List[CohortMetric] = Field(default_factory=list)
    recommendation_performance: List[CohortMetric] = Field(default_factory=list)
    score_bucket_performance: List[CohortMetric] = Field(default_factory=list)
    source_performance: List[CohortMetric] = Field(default_factory=list)
    response_times: List[ResponseTimeMetrics] = Field(default_factory=list)
    generated_at: datetime = Field(default_factory=utc_now)
