"""Pydantic schemas for Local Interactive Browser Agent protocol and Device Pairing."""

from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class PairingCodeResponse(BaseModel):
    """Generated short-lived pairing code response for dashboard user."""
    device_id: str
    pairing_code: str
    expires_at: datetime
    server_url: Optional[str] = None
    instructions: str
    cli_command: str


class PairDeviceRequest(BaseModel):
    """Device pairing request submitted by the local agent CLI."""
    pairing_code: str = Field(..., description="6-digit pairing code shown in dashboard")
    device_name: Optional[str] = Field(default="Local Interactive Machine", description="Hostname or user-friendly device name")
    agent_version: str = Field(default="1.0.0", description="Agent runtime version")
    capabilities: List[str] = Field(
        default_factory=lambda: ["playwright_chromium", "visible_browser", "interactive_captcha", "mfa_login"],
        description="Supported browser automation capabilities",
    )


class PairDeviceResponse(BaseModel):
    """Pairing response containing cryptographic device token."""
    success: bool
    device_id: str
    device_token: str
    device_name: str
    server_url: str
    message: str


class DeviceStatusResponse(BaseModel):
    """Status details of a paired device for UI display."""
    device_id: str
    device_name: str
    status: str
    is_active: bool
    last_seen_at: Optional[datetime] = None
    capabilities: List[str] = Field(default_factory=list)
    agent_version: str = "1.0.0"
    created_at: Optional[datetime] = None


class AgentTaskPollResponse(BaseModel):
    """Response returned when local agent polls for authorized tasks."""
    has_task: bool
    task: Optional[Dict[str, Any]] = None


class AgentTaskStatusUpdate(BaseModel):
    """Heartbeat or blocker update from local agent."""
    task_id: str
    status: str
    pause_reason: Optional[str] = None
    failure_reason: Optional[str] = None


class AgentTaskPackageSubmit(BaseModel):
    """Pre-submission package generated by local agent."""
    task_id: str
    fields_detected_count: int = 0
    fields_filled_count: int = 0
    fields_requiring_input_count: int = 0
    review_package_json: Dict[str, Any] = Field(default_factory=dict)
    screenshot_base64: Optional[str] = None


class AgentTaskCompleteSubmit(BaseModel):
    """Verified submission completion evidence from local agent."""
    task_id: str
    submission_reference: Optional[str] = None
    employer_confirmation_signal: str
    evidence_notes: Optional[str] = None
